import { DatePipe } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { DomSanitizer, SafeUrl } from '@angular/platform-browser';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { AuthService } from '../../core/services/auth.service';
import { TwoFactorSetup } from '../../core/models/auth.model';
import { User } from '../../core/models/user.model';

@Component({
  selector: 'app-profile',
  standalone: true,
  imports: [ReactiveFormsModule, DatePipe],
  templateUrl: './profile.component.html',
  styleUrl: './profile.component.css',
})
export class ProfileComponent {
  private readonly auth = inject(AuthService);
  private readonly fb = inject(FormBuilder);
  private readonly sanitizer = inject(DomSanitizer);

  readonly user = signal<User | null>(null);
  readonly setup = signal<TwoFactorSetup | null>(null);
  readonly qrImage = signal<SafeUrl | null>(null);
  readonly recoveryCodes = signal<string[] | null>(null);
  readonly disabling = signal(false);
  readonly busy = signal(false);
  readonly errorMessage = signal<string | null>(null);
  readonly savedCodes = signal(false);
  readonly copied = signal(false);

  readonly codeForm = this.fb.nonNullable.group({
    code: ['', [Validators.required, Validators.minLength(6)]],
  });

  constructor() {
    this.auth.me().subscribe((user) => this.user.set(user));
  }

  startSetup(): void {
    this.busy.set(true);
    this.errorMessage.set(null);
    this.auth.setupTwoFactor().subscribe({
      next: (setup) => {
        this.setup.set(setup);
        // The image is generated by our own API from the provisioning URI.
        this.qrImage.set(this.sanitizer.bypassSecurityTrustUrl(setup.qr_data_uri));
        this.codeForm.reset();
        this.busy.set(false);
      },
      error: (err) => this.fail(err, 'Could not start setup. Please try again.'),
    });
  }

  cancelSetup(): void {
    this.setup.set(null);
    this.qrImage.set(null);
    this.errorMessage.set(null);
  }

  confirmSetup(): void {
    if (this.codeForm.invalid) {
      this.codeForm.markAllAsTouched();
      return;
    }

    this.busy.set(true);
    this.errorMessage.set(null);
    this.auth.enableTwoFactor(this.codeForm.getRawValue().code).subscribe({
      next: (result) => {
        this.recoveryCodes.set(result.recovery_codes);
        this.savedCodes.set(false);
        this.copied.set(false);
        this.cancelSetup();
        this.user.update((user) => (user ? { ...user, two_factor_enabled: true } : user));
        this.busy.set(false);
      },
      error: (err) => this.fail(err, 'That code did not match. Check the app and try again.'),
    });
  }

  startDisabling(): void {
    this.disabling.set(true);
    this.codeForm.reset();
    this.errorMessage.set(null);
  }

  cancelDisabling(): void {
    this.disabling.set(false);
    this.errorMessage.set(null);
  }

  confirmDisabling(): void {
    if (this.codeForm.invalid) {
      this.codeForm.markAllAsTouched();
      return;
    }

    this.busy.set(true);
    this.errorMessage.set(null);
    this.auth.disableTwoFactor(this.codeForm.getRawValue().code).subscribe({
      next: () => {
        this.user.update((user) => (user ? { ...user, two_factor_enabled: false } : user));
        this.disabling.set(false);
        this.busy.set(false);
      },
      error: (err) => this.fail(err, 'That code is not right. Try again.'),
    });
  }

  async copyRecoveryCodes(): Promise<void> {
    await navigator.clipboard.writeText((this.recoveryCodes() ?? []).join('\n'));
    this.copied.set(true);
  }

  downloadRecoveryCodes(): void {
    const codes = (this.recoveryCodes() ?? []).join('\n');
    const text = `LegalLens recovery codes for ${this.user()?.email}\nEach code works once.\n\n${codes}\n`;
    const link = document.createElement('a');
    link.href = URL.createObjectURL(new Blob([text], { type: 'text/plain' }));
    link.download = 'legallens-recovery-codes.txt';
    link.click();
    URL.revokeObjectURL(link.href);
  }

  finishRecoveryCodes(): void {
    this.recoveryCodes.set(null);
  }

  private fail(err: { error?: { detail?: string } }, fallback: string): void {
    this.errorMessage.set(err?.error?.detail ?? fallback);
    this.busy.set(false);
  }
}
